# Not Use
version: 0.2

env:
    variables:
        NODE_ENV: "production"

phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ECR
    build:
        commands:
            - echo Build started on `date`
            - docker build -t auction-house .
            - docker tag auction-house:latest $AWS_ECR/auction-house:latest
            - echo Build completed on `date`

    post_build:
        commands:
            - echo aws ecr get-login-password --region ap-southeast-2
            - echo $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
            - echo Pushing the Docker image
            - docker push $AWS_ECR/auction-house:latest
            - echo push completed on `date`
]